//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterRemedy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bathproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bathproduct()
        {
            this.Bathalternative = new HashSet<Bathalternative>();
        }
    
        public int ba_product_id { get; set; }
        public string chemical { get; set; }
        public int Bathroom_bath_id { get; set; }
    
        public virtual Bathroom Bathroom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bathalternative> Bathalternative { get; set; }
    }
}
