//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterRemedy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitproduct()
        {
            this.Kitalternative = new HashSet<Kitalternative>();
        }
    
        public int kit_product_id { get; set; }
        public string chemical { get; set; }
        public int Kitchen_kitchen_id { get; set; }
    
        public virtual Kitchen Kitchen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kitalternative> Kitalternative { get; set; }
    }
}
