//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterRemedy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Launalternative
    {
        public int alter_id { get; set; }
        public string name { get; set; }
        public int Launproduct_laun_id { get; set; }
    
        public virtual Launproduct Launproduct { get; set; }
    }
}
