//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterRemedy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class waterremedyModelContainer : DbContext
    {
        public waterremedyModelContainer()
            : base("name=waterremedyModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Bathroom> BathroomSet { get; set; }
        public virtual DbSet<Bathproduct> BathproductSet { get; set; }
        public virtual DbSet<Bathalternative> BathalternativeSet { get; set; }
        public virtual DbSet<Kitchen> KitchenSet { get; set; }
        public virtual DbSet<Kitproduct> KitproductSet { get; set; }
        public virtual DbSet<Kitalternative> KitalternativeSet { get; set; }
        public virtual DbSet<Laundry> LaundrySet { get; set; }
        public virtual DbSet<Launproduct> LaunproductSet { get; set; }
        public virtual DbSet<Launalternative> LaunalternativeSet { get; set; }
        public virtual DbSet<Rainfall> RainfallSet { get; set; }
    }
}
